[package]
name = "Kernel_Driver_Exploit"
version = "0.1.0"
edition = "2023"
authro = ["michredteam <github.com/michredteam>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winapi = {version = "0.3.9", features=["fileapi", "ioapiset", "memoryapi"]}
