[package]
name = "keyboard_hooking"
version = "0.1.0"
authors = ["michredteam <github.com/michredteam>"]
edition = "2023"

[[bin]]
name = "keyboard_hooking"
path = "src/main.rs"

[dependencies]
windows = {version = "0.43.0", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging"]}